### ISSUE TITLE
UI.R: Uniform naming of IDs

### ISSUE THREAD

**Issue by discoleo** [adrian0010/Percolation#2]
# Uniform Naming of IDs

The ID names will have to be named uniformly:
- txtTitle, probSimple: rename to txtTitleSimple, probSimple;
- plotOutput: rename function also to "PercolationSimple";
- rename the corresponding entries in Server.R as well;

**Comment by adrian0010** [comment]
cum vreti sa redenumesc probSimple,pentru ca mi-ati dat acelasi nume?
